# Generated by Django 6.0.5 on 2026-07-21 04:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_management', '0018_subject_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlanSubmoduleLimit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_limit', models.PositiveIntegerField(blank=True, help_text='Max questions available per quiz for this submodule on this plan. Blank = no limit.', null=True)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submodule_limits', to='student_management.subscriptionplan')),
                ('submodule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plan_limits', to='student_management.submodule')),
            ],
            options={
                'unique_together': {('plan', 'submodule')},
            },
        ),
    ]
