# Generated by Django 6.0.5 on 2026-07-21 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_management', '0019_plansubmodulelimit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscriptionplan',
            name='submodules',
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='submodules',
            field=models.ManyToManyField(
                blank=True,
                related_name='subscription_plans',
                through='student_management.PlanSubmoduleLimit',
                to='student_management.submodule',
            ),
        ),
    ]