# Generated by Django 6.0.5 on 2026-07-22 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_management', '0020_alter_subscriptionplan_submodules'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='last_expiry_reminder_sent',
            field=models.DateField(blank=True, null=True),
        ),
    ]
