# Generated by Django 6.0.5 on 2026-07-24 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_management', '0021_payment_last_expiry_reminder_sent'),
    ]

    operations = [
        migrations.AddField(
            model_name='plansubmodulelimit',
            name='is_override',
            field=models.BooleanField(default=False, help_text="True: this submodule was given its own explicit limit and always uses question_limit, ignoring the plan's shared limit. False: this submodule has no explicit limit of its own and simply follows the plan's shared limit (question_limit here is just a copy of that shared value)."),
        ),
    ]
