# Generated by Django 6.0.5 on 2026-08-05 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_management', '0022_plansubmodulelimit_is_override'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptionplan',
            name='subject_chapters',
            field=models.JSONField(blank=True, default=dict, help_text="Optional manual chapter names per subject. Format: {subject_id: 'one chapter per line'}.", null=True),
        ),
    ]
