# Generated by Django 6.0.2 on 2026-09-28 04:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_management', '0023_subscriptionplan_subject_chapters'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='credit_applied',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AddField(
            model_name='payment',
            name='upgraded_from',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='upgrades', to='student_management.payment'),
        ),
    ]
